// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaQWTb8BdSro1HaKVSdQvmbvND9b_MQ5c',
    appId: '1:321220335408:web:87c35244eec0ce95cfdaf5',
    messagingSenderId: '321220335408',
    projectId: 'miles-92ac8',
    authDomain: 'miles-92ac8.firebaseapp.com',
    storageBucket: 'miles-92ac8.firebasestorage.app',
    measurementId: 'G-65JNFCE2BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtyPVUvBiyoW48A1utijDiL0CczD3nDfM',
    appId: '1:321220335408:android:dba58e998fdd9402cfdaf5',
    messagingSenderId: '321220335408',
    projectId: 'miles-92ac8',
    storageBucket: 'miles-92ac8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK1bpPNeM_Wuhi62lC-RlnBAsmqrLwSso',
    appId: '1:321220335408:ios:e408de3364a710cccfdaf5',
    messagingSenderId: '321220335408',
    projectId: 'miles-92ac8',
    storageBucket: 'miles-92ac8.firebasestorage.app',
    iosBundleId: 'com.example.milesEducationApp',
  );
}
